# Generated by Django 4.1.2 on 2022-12-22 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazivKategorije', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Kviz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('opisKviza', models.CharField(max_length=255)),
                ('kategorije', models.ManyToManyField(to='main.kategorija')),
            ],
        ),
        migrations.CreateModel(
            name='OpisPitanja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tekst', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pitanje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odgovor1', models.CharField(max_length=150)),
                ('odgovor2', models.CharField(max_length=150)),
                ('odgovor3', models.CharField(max_length=150)),
                ('odgovor4', models.CharField(max_length=150)),
                ('tocan', models.IntegerField()),
                ('savjet', models.CharField(max_length=255)),
                ('kviz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kviz')),
                ('opis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.opispitanja')),
            ],
        ),
    ]
