# Generated by Django 4.1.2 on 2022-12-22 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_pitanje_naziv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opispitanja',
            name='spajanjeNaPitanje',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.pitanje'),
            preserve_default=False,
        ),
    ]
