# Generated by Django 4.1.2 on 2022-12-22 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_opispitanja_spajanjenapitanje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opispitanja',
            name='spajanjeNaPitanje',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pitanje'),
        ),
    ]
