# Generated by Django 4.1.2 on 2022-12-22 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_opispitanja_spajanjenapitanje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opispitanja',
            name='spajanjeNaPitanje',
        ),
    ]
