# Generated by Django 4.1.2 on 2023-03-30 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_opispitanja_spajanjenapitanje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opispitanja',
            name='tekst',
            field=models.CharField(max_length=255),
        ),
    ]
